document.write("D<br>")
document.write("14 años<br>")
document.write("901<br>")
document.write("3052131551<br>")
document.write("Diagonal 52 a sur N° 53-74<br>")
document.write("diegocamilonavarro901@gmail.com<br>")
document.write("09/02/2007<br>")
document.write("Bogotá<br>")
console.log("Ingles")
console.log("Wandavision")
